#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent
# Spec: 001-claude-md - AI Audit AX Platform

set -e

echo "========================================"
echo "Starting Development Environment"
echo "AI Audit AX Platform"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Project root
PROJECT_ROOT="/Users/jaewookim/Desktop/Personal Coding/AI Audit"

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start on port $port${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready on port $port${NC}"
}

# Check environment variables
check_env() {
    echo ""
    echo "Checking environment variables..."

    # Frontend
    if [ -f "$PROJECT_ROOT/frontend/.env" ] || [ -f "$PROJECT_ROOT/frontend/.env.local" ]; then
        echo -e "${GREEN}Frontend .env found${NC}"
    else
        echo -e "${YELLOW}Warning: Frontend .env not found${NC}"
    fi

    # Backend
    if [ -f "$PROJECT_ROOT/backend/.env" ]; then
        echo -e "${GREEN}Backend .env found${NC}"
    else
        echo -e "${YELLOW}Warning: Backend .env not found${NC}"
    fi
}

# ============================================
# START SERVICES
# ============================================

start_frontend() {
    echo ""
    echo "Starting Frontend (Next.js)..."
    cd "$PROJECT_ROOT/frontend"

    # Install dependencies if needed
    if [ ! -d "node_modules" ]; then
        echo "Installing frontend dependencies..."
        npm install
    fi

    # Start dev server in background
    npm run dev &
    FRONTEND_PID=$!
    echo "Frontend PID: $FRONTEND_PID"

    wait_for_service 3000 "Frontend"
}

start_backend() {
    echo ""
    echo "Starting Backend (FastAPI)..."
    cd "$PROJECT_ROOT/backend"

    # Activate virtual environment if exists
    if [ -d "venv" ]; then
        source venv/bin/activate
        echo -e "${GREEN}Virtual environment activated${NC}"
    else
        echo -e "${YELLOW}Warning: No venv found, using system Python${NC}"
    fi

    # Start uvicorn in background
    python -m uvicorn src.main:app --reload --port 8000 &
    BACKEND_PID=$!
    echo "Backend PID: $BACKEND_PID"

    wait_for_service 8000 "Backend"
}

# ============================================
# MAIN
# ============================================

main() {
    check_env

    echo ""
    echo "========================================"
    echo "Starting Services..."
    echo "========================================"

    start_backend
    start_frontend

    echo ""
    echo "========================================"
    echo -e "${GREEN}Environment Ready!${NC}"
    echo "========================================"
    echo ""
    echo "Services:"
    echo "  Frontend:  http://localhost:3000"
    echo "  Backend:   http://localhost:8000"
    echo "  API Docs:  http://localhost:8000/docs"
    echo ""
    echo "Press Ctrl+C to stop all services"
    echo ""

    # Wait for interrupt
    wait
}

# Cleanup function
cleanup() {
    echo ""
    echo "Stopping services..."

    # Kill background processes
    if [ ! -z "$FRONTEND_PID" ]; then
        kill $FRONTEND_PID 2>/dev/null || true
    fi
    if [ ! -z "$BACKEND_PID" ]; then
        kill $BACKEND_PID 2>/dev/null || true
    fi

    # Kill any remaining processes on ports
    lsof -ti:3000 | xargs kill -9 2>/dev/null || true
    lsof -ti:8000 | xargs kill -9 2>/dev/null || true

    echo -e "${GREEN}Services stopped${NC}"
}

trap cleanup EXIT INT TERM

main
